CREATE OR REPLACE WAREHOUSE CUSTOMER_OPS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE CUSTOMER_OPS_DB;
CREATE OR REPLACE SCHEMA CUSTOMER_OPS_DB.RAW;
CREATE OR REPLACE SCHEMA CUSTOMER_OPS_DB.TRANSFORM;
CREATE OR REPLACE SCHEMA CUSTOMER_OPS_DB.MART;
SHOW SCHEMAS IN DATABASE CUSTOMER_OPS_DB;

USE SCHEMA CUSTOMER_OPS_DB.RAW;
CREATE OR REPLACE STAGE CUSTOMER_OPS_STAGE
 FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY='"');


CREATE OR REPLACE TABLE CUSTOMER_RAW (
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    COUNTRY STRING
);
CREATE OR REPLACE TABLE CUSTOMER_RAW (
 CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    AGE_GROUP STRING,
    GENDER STRING,
    CITY STRING,
    PROVINCE STRING,
    SEGMENT STRING,
    SIGNUP_DATE DATE,
    CONTRACT_TYPE STRING,
    TENURE_MONTHS NUMBER
);
USE WAREHOUSE CUSTOMER_OPS_WH;
USE SCHEMA CUSTOMER_OPS_DB.RAW;

-- STEP A: REMAINING RAW TABLES
CREATE OR REPLACE TABLE INTERACTIONS_RAW (
 INTERACTION_ID      STRING,
    CUSTOMER_ID         NUMBER,
    CASE_ID             STRING,
    INTERACTION_DATE    DATE,
    CHANNEL             STRING,
    ISSUE_TYPE          STRING,
    ISSUE_SUBTYPE       STRING,
    PRIORITY            STRING,
    AGENT_ID            STRING,
    INTERACTION_STATUS  STRING
);
CREATE OR REPLACE TABLE OUTCOMES_RAW (
 OUTCOME_ID                STRING,
    CASE_ID                   STRING,
    CUSTOMER_ID               NUMBER,
    RESOLVED_FLAG             NUMBER,
    RESOLUTION_TIME_HOURS     FLOAT,
    REPEAT_CONTACT_30D_FLAG   NUMBER,
    REFUND_FLAG               NUMBER,
    CHURN_RISK_FLAG           NUMBER,
    SLA_BREACH_FLAG           NUMBER,
    FINAL_STATUS              STRING
);

CREATE OR REPLACE TABLE SERVICE_EVENTS_RAW (
 EVENT_ID            STRING,
    CASE_ID             STRING,
    CUSTOMER_ID         NUMBER,
    CREATED_DATE        DATE,
    ASSIGNED_DATE       TIMESTAMP_NTZ,
    FIRST_RESPONSE_DATE TIMESTAMP_NTZ,
    RESOLVED_DATE       TIMESTAMP_NTZ,
    TEAM_NAME           STRING,
    ROOT_CAUSE          STRING,
    ESCALATION_FLAG     NUMBER
);

CREATE OR REPLACE TABLE SURVEYS_RAW (
    SURVEY_ID           STRING,
    CUSTOMER_ID         NUMBER,
    CASE_ID             STRING,
    SURVEY_DATE         DATE,
    CSAT_SCORE          NUMBER,
    NPS_GROUP           STRING,
    SENTIMENT_LABEL     STRING,
    FEEDBACK_TEXT       STRING,
    RESPONSE_CHANNEL    STRING,
    RESPONDED_FLAG      NUMBER
);

SHOW TABLES IN SCHEMA CUSTOMER_OPS_DB.RAW;

USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE TABLE CUSTOMER_RAW (
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   STRING,
    AGE_GROUP       STRING,
    GENDER          STRING,
    CITY            STRING,
    PROVINCE        STRING,
    SEGMENT         STRING,
    SIGNUP_DATE     DATE,
    CONTRACT_TYPE   STRING,
    TENURE_MONTHS   NUMBER
);
DESC TABLE CUSTOMER_RAW;

USE WAREHOUSE CUSTOMER_OPS_WH;
USE SCHEMA CUSTOMER_OPS_DB.RAW;

-- First confirm the stage has your file
LIST @CUSTOMER_OPS_STAGE;

USE SCHEMA CUSTOMER_OPS_DB.RAW;
CREATE OR REPLACE TABLE INTERACTIONS_RAW (
    INTERACTION_ID     STRING,
    CUSTOMER_ID        NUMBER,
    CASE_ID            STRING,
    INTERACTION_DATE   DATE,
    CHANNEL            STRING,
    ISSUE_TYPE         STRING,
    ISSUE_SUBTYPE      STRING,
    PRIORITY           STRING,
    AGENT_ID           STRING,
    INTERACTION_STATUS STRING
);

CREATE OR REPLACE TABLE OUTCOMES_RAW (
    OUTCOME_ID              STRING,
    CASE_ID                 STRING,
    CUSTOMER_ID             NUMBER,
    RESOLVED_FLAG           NUMBER,
    RESOLUTION_TIME_HOURS   FLOAT,
    REPEAT_CONTACT_30D_FLAG NUMBER,
    REFUND_FLAG             NUMBER,
    CHURN_RISK_FLAG         NUMBER,
    SLA_BREACH_FLAG         NUMBER,
    FINAL_STATUS            STRING
);

CREATE OR REPLACE TABLE SERVICE_EVENTS_RAW (
    EVENT_ID            STRING,
    CASE_ID             STRING,
    CUSTOMER_ID         NUMBER,
    CREATED_DATE        DATE,
    ASSIGNED_DATE       TIMESTAMP_NTZ,
    FIRST_RESPONSE_DATE TIMESTAMP_NTZ,
    RESOLVED_DATE       TIMESTAMP_NTZ,
    TEAM_NAME           STRING,
    ROOT_CAUSE          STRING,
    ESCALATION_FLAG     NUMBER
);

CREATE OR REPLACE TABLE SURVEYS_RAW (
    SURVEY_ID        STRING,
    CUSTOMER_ID      NUMBER,
    CASE_ID          STRING,
    SURVEY_DATE      DATE,
    CSAT_SCORE       NUMBER,
    NPS_GROUP        STRING,
    SENTIMENT_LABEL  STRING,
    FEEDBACK_TEXT    STRING,
    RESPONSE_CHANNEL STRING,
    RESPONDED_FLAG   NUMBER
);

SHOW TABLES IN SCHEMA CUSTOMER_OPS_DB.RAW;


USE SCHEMA CUSTOMER_OPS_DB.MART;
CREATE OR REPLACE VIEW MART_CASE_SUMMARY AS
SELECT
    i.CASE_ID,
    i.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.AGE_GROUP,
    c.GENDER,
    c.CITY,
    c.PROVINCE,
    c.SEGMENT,
    c.CONTRACT_TYPE,
    c.TENURE_MONTHS,
    i.INTERACTION_DATE,
    i.CHANNEL,
    i.ISSUE_TYPE,
    i.ISSUE_SUBTYPE,
    i.PRIORITY,
    i.AGENT_ID,
    i.INTERACTION_STATUS,
    o.RESOLVED_FLAG,
    o.RESOLUTION_TIME_HOURS,
    o.REPEAT_CONTACT_30D_FLAG,
    o.REFUND_FLAG,
    o.CHURN_RISK_FLAG,
    o.SLA_BREACH_FLAG,
    o.FINAL_STATUS,
    e.TEAM_NAME,
    e.ROOT_CAUSE,
    e.ESCALATION_FLAG,
    DATEDIFF('minute', e.ASSIGNED_DATE, e.FIRST_RESPONSE_DATE) AS RESPONSE_TIME_MINS,
    DATEDIFF('hour',   e.CREATED_DATE,  e.RESOLVED_DATE)       AS FULL_CYCLE_HOURS,
    sv.CSAT_SCORE,
    sv.NPS_GROUP,
    sv.SENTIMENT_LABEL,
    sv.FEEDBACK_TEXT,
    sv.RESPONDED_FLAG,
    CASE WHEN o.CHURN_RISK_FLAG = 1 AND o.REPEAT_CONTACT_30D_FLAG = 1
         THEN 1 ELSE 0 END                  AS HIGH_RISK_FLAG,
    CASE WHEN sv.CSAT_SCORE <= 2 THEN 'Low'
         WHEN sv.CSAT_SCORE  = 3 THEN 'Mid'
         ELSE 'High' END                    AS CSAT_BAND
FROM CUSTOMER_OPS_DB.RAW.INTERACTIONS_RAW   i
LEFT JOIN CUSTOMER_OPS_DB.RAW.CUSTOMER_RAW       c  ON i.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN CUSTOMER_OPS_DB.RAW.OUTCOMES_RAW       o  ON i.CASE_ID     = o.CASE_ID
LEFT JOIN CUSTOMER_OPS_DB.RAW.SERVICE_EVENTS_RAW e  ON i.CASE_ID     = e.CASE_ID
LEFT JOIN CUSTOMER_OPS_DB.RAW.SURVEYS_RAW        sv ON i.CASE_ID     = sv.CASE_ID;

SELECT
    COUNT(*)                             AS TOTAL_CASES,
    ROUND(AVG(CSAT_SCORE), 2)            AS AVG_CSAT,
    ROUND(AVG(RESOLUTION_TIME_HOURS), 2) AS AVG_RESOLUTION_HRS,
    COUNT(DISTINCT CUSTOMER_ID)          AS TOTAL_CUSTOMERS
FROM CUSTOMER_OPS_DB.MART.MART_CASE_SUMMARY;

SELECT CURRENT_ACCOUNT();

USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE STAGE AZURE_BLOB_STAGE
    URL = 'azure://customeropsstore.blob.core.windows.net/raw-data'
    CREDENTIALS = (
        AZURE_SAS_TOKEN = '[YOUR_AZURE_SAS_TOKEN_HERE]'
    )
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('', 'NULL', 'nan')
    );

   USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE STAGE AZURE_BLOB_STAGE
    URL = 'azure://customeropsstore.blob.core.windows.net/raw-data'
    CREDENTIALS = (
        AZURE_SAS_TOKEN = '[YOUR_AZURE_SAS_TOKEN_HERE]'
    )
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('', 'NULL', 'nan')
    );

    LIST @CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE;

    USE SCHEMA CUSTOMER_OPS_DB.RAW;
SHOW STAGES;


USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE STAGE CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE
    URL = 'azure://customeropsstore.blob.core.windows.net/raw-data'
    CREDENTIALS = (
        AZURE_SAS_TOKEN = '[YOUR_AZURE_SAS_TOKEN_HERE]'
    )
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('', 'NULL', 'nan')
    );

-- Then verify
LIST @CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE;


USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE STAGE CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE
    URL = 'azure://customeropsstore.blob.core.windows.net/raw-data'
    CREDENTIALS = (
        AZURE_SAS_TOKEN = '[YOUR_AZURE_SAS_TOKEN_HERE]'
    )
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('', 'NULL', 'nan')
    );

    USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE STAGE CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE
    URL = 'azure://customeropsstore.blob.core.windows.net/raw-data'
    CREDENTIALS = (
        AZURE_SAS_TOKEN = '[YOUR_AZURE_SAS_TOKEN_HERE]'
    )
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('', 'NULL', 'nan')
    );

    LIST @CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE;

    USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE STAGE CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE
    URL = 'azure://customeropsstore.blob.core.windows.net/raw-data'
    CREDENTIALS = (
        AZURE_SAS_TOKEN = '[YOUR_AZURE_SAS_TOKEN_HERE]'
    )
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('', 'NULL', 'nan')
    );

LIST @CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE;


USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE STAGE CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE
    URL = 'azure://customeropsstore.blob.core.windows.net/raw-data'
    CREDENTIALS = (
        AZURE_SAS_TOKEN ='[YOUR_AZURE_SAS_TOKEN_HERE]'
    )
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('', 'NULL', 'nan')
    );

    LIST @CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE;

    USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE STAGE CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE
    URL = 'azure://customeropsstore.blob.core.windows.net/raw-data'
    CREDENTIALS = (
        AZURE_ACCOUNT_NAME = '[YOUR_AZURE_ACCOUNT_NAME]
        AZURE_ACCOUNT_KEY = '[YOUR_AZURE_ACCOUNT_KEY_HERE]'
    )
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('', 'NULL', 'nan')
    );

LIST @CUSTOMER_OPS_DB.RAW.AZURE_BLOB_STAGE;

USE SCHEMA CUSTOMER_OPS_DB.RAW;

-- Drop the failing external stage
DROP STAGE IF EXISTS AZURE_BLOB_STAGE;

-- Create a simple internal stage to document the Azure connection
CREATE OR REPLACE STAGE AZURE_BLOB_STAGE
    COMMENT = 'Represents Azure Blob Storage raw-data container: azure://customeropsstore.blob.core.windows.net/raw-data';


    USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE STAGE AWS_S3_STAGE
    URL = 's3://customer-ops-raw-data/'
    CREDENTIALS = (
        AWS_KEY_ID = '[YOUR_AWS_KEY_ID_HERE]'
        AWS_SECRET_KEY = '[YOUR_AWS_SECRET_KEY_HERE]'
    )
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('', 'NULL', 'nan')
    );

LIST @CUSTOMER_OPS_DB.RAW.AWS_S3_STAGE;

USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE STAGE AWS_S3_STAGE
    URL = 's3://customer-ops-raw-data/'
    CREDENTIALS = (
        AWS_KEY_ID = '[YOUR_AWS_KEY_ID_HERE]'
        AWS_SECRET_KEY ='[YOUR_AWS_SECRET_KEY_HERE]'
    )
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('', 'NULL', 'nan')
    );
    LIST @CUSTOMER_OPS_DB.RAW.AWS_S3_STAGE;

    USE SCHEMA CUSTOMER_OPS_DB.RAW;

-- Load customers from S3
COPY INTO CUSTOMER_RAW
    FROM @AWS_S3_STAGE/customers_clean.csv
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('', 'NULL', 'nan')
        DATE_FORMAT = 'YYYY-MM-DD'
    )
    ON_ERROR = 'CONTINUE';

-- Verify
SELECT COUNT(*) AS rows_from_s3 FROM CUSTOMER_RAW;