-- ============================================================================
-- CUSTOMER OPS PLATFORM - TRANSFORMATION & MART LAYER
-- File: 04_create_views.sql
-- Purpose: Create transformation views and analytical MART tables
-- ============================================================================
 
USE WAREHOUSE CUSTOMER_OPS_WH;
USE SCHEMA CUSTOMER_OPS_DB.MART;
 
-- ============================================================================
-- SECTION 1: CREATE MAIN ANALYTICAL VIEW
-- ============================================================================
 
CREATE OR REPLACE VIEW MART_CASE_SUMMARY AS
SELECT
    i.CASE_ID,
    i.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.AGE_GROUP,
    c.GENDER,
    c.CITY,
    c.PROVINCE,
    c.SEGMENT,
    c.CONTRACT_TYPE,
    c.TENURE_MONTHS,
    i.INTERACTION_DATE,
    i.CHANNEL,
    i.ISSUE_TYPE,
    i.ISSUE_SUBTYPE,
    i.PRIORITY,
    i.AGENT_ID,
    i.INTERACTION_STATUS,
    o.RESOLVED_FLAG,
    o.RESOLUTION_TIME_HOURS,
    o.REPEAT_CONTACT_30D_FLAG,
    o.REFUND_FLAG,
    o.CHURN_RISK_FLAG,
    o.SLA_BREACH_FLAG,
    o.FINAL_STATUS,
    e.TEAM_NAME,
    e.ROOT_CAUSE,
    e.ESCALATION_FLAG,
    DATEDIFF('minute', e.ASSIGNED_DATE, e.FIRST_RESPONSE_DATE) AS RESPONSE_TIME_MINS,
    DATEDIFF('hour', e.CREATED_DATE, e.RESOLVED_DATE) AS FULL_CYCLE_HOURS,
    sv.CSAT_SCORE,
    sv.NPS_GROUP,
    sv.SENTIMENT_LABEL,
    sv.FEEDBACK_TEXT,
    sv.RESPONDED_FLAG,
    CASE WHEN o.CHURN_RISK_FLAG = 1 AND o.REPEAT_CONTACT_30D_FLAG = 1
         THEN 1 ELSE 0 END AS HIGH_RISK_FLAG,
    CASE WHEN sv.CSAT_SCORE <= 2 THEN 'Low'
         WHEN sv.CSAT_SCORE = 3 THEN 'Mid'
         ELSE 'High' END AS CSAT_BAND
FROM CUSTOMER_OPS_DB.RAW.INTERACTIONS_RAW i
LEFT JOIN CUSTOMER_OPS_DB.RAW.CUSTOMER_RAW c ON i.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN CUSTOMER_OPS_DB.RAW.OUTCOMES_RAW o ON i.CASE_ID = o.CASE_ID
LEFT JOIN CUSTOMER_OPS_DB.RAW.SERVICE_EVENTS_RAW e ON i.CASE_ID = e.CASE_ID
LEFT JOIN CUSTOMER_OPS_DB.RAW.SURVEYS_RAW sv ON i.CASE_ID = sv.CASE_ID;
 
-- ============================================================================
-- SECTION 2: CREATE CUSTOMER ANALYTICS VIEW
-- ============================================================================
 
CREATE OR REPLACE VIEW MART_CUSTOMER_ANALYTICS AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.SEGMENT,
    c.AGE_GROUP,
    c.PROVINCE,
    c.TENURE_MONTHS,
    COUNT(DISTINCT i.CASE_ID) AS TOTAL_CASES,
    ROUND(AVG(o.RESOLUTION_TIME_HOURS), 2) AS AVG_RESOLUTION_TIME,
    ROUND(SUM(CASE WHEN o.RESOLVED_FLAG = 1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS RESOLUTION_RATE,
    ROUND(AVG(sv.CSAT_SCORE), 2) AS AVG_CSAT,
    SUM(CASE WHEN o.CHURN_RISK_FLAG = 1 THEN 1 ELSE 0 END) AS CHURN_RISK_COUNT,
    SUM(CASE WHEN o.REPEAT_CONTACT_30D_FLAG = 1 THEN 1 ELSE 0 END) AS REPEAT_CONTACT_COUNT,
    SUM(CASE WHEN o.REFUND_FLAG = 1 THEN 1 ELSE 0 END) AS REFUND_COUNT
FROM CUSTOMER_OPS_DB.RAW.CUSTOMER_RAW c
LEFT JOIN CUSTOMER_OPS_DB.RAW.INTERACTIONS_RAW i ON c.CUSTOMER_ID = i.CUSTOMER_ID
LEFT JOIN CUSTOMER_OPS_DB.RAW.OUTCOMES_RAW o ON i.CASE_ID = o.CASE_ID
LEFT JOIN CUSTOMER_OPS_DB.RAW.SURVEYS_RAW sv ON i.CASE_ID = sv.CASE_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.SEGMENT, c.AGE_GROUP, c.PROVINCE, c.TENURE_MONTHS;
 
-- ============================================================================
-- SECTION 3: CREATE CHANNEL PERFORMANCE VIEW
-- ============================================================================
 
CREATE OR REPLACE VIEW MART_CHANNEL_PERFORMANCE AS
SELECT
    i.CHANNEL,
    COUNT(DISTINCT i.INTERACTION_ID) AS TOTAL_INTERACTIONS,
    COUNT(DISTINCT i.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    ROUND(SUM(CASE WHEN o.RESOLVED_FLAG = 1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS RESOLUTION_RATE,
    ROUND(AVG(o.RESOLUTION_TIME_HOURS), 2) AS AVG_RESOLUTION_TIME,
    ROUND(AVG(sv.CSAT_SCORE), 2) AS AVG_CSAT_SCORE,
    SUM(CASE WHEN o.SLA_BREACH_FLAG = 1 THEN 1 ELSE 0 END) AS SLA_BREACH_COUNT
FROM CUSTOMER_OPS_DB.RAW.INTERACTIONS_RAW i
LEFT JOIN CUSTOMER_OPS_DB.RAW.OUTCOMES_RAW o ON i.CASE_ID = o.CASE_ID
LEFT JOIN CUSTOMER_OPS_DB.RAW.SURVEYS_RAW sv ON i.CASE_ID = sv.CASE_ID
GROUP BY i.CHANNEL;
 
-- ============================================================================
-- SECTION 4: CREATE AGENT PERFORMANCE VIEW
-- ============================================================================
 
CREATE OR REPLACE VIEW MART_AGENT_PERFORMANCE AS
SELECT
    i.AGENT_ID,
    COUNT(DISTINCT i.INTERACTION_ID) AS TOTAL_INTERACTIONS,
    COUNT(DISTINCT i.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    ROUND(SUM(CASE WHEN o.RESOLVED_FLAG = 1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS RESOLUTION_RATE,
    ROUND(AVG(o.RESOLUTION_TIME_HOURS), 2) AS AVG_RESOLUTION_TIME,
    ROUND(AVG(sv.CSAT_SCORE), 2) AS AVG_CSAT_SCORE,
    SUM(CASE WHEN e.ESCALATION_FLAG = 1 THEN 1 ELSE 0 END) AS ESCALATION_COUNT
FROM CUSTOMER_OPS_DB.RAW.INTERACTIONS_RAW i
LEFT JOIN CUSTOMER_OPS_DB.RAW.OUTCOMES_RAW o ON i.CASE_ID = o.CASE_ID
LEFT JOIN CUSTOMER_OPS_DB.RAW.SURVEYS_RAW sv ON i.CASE_ID = sv.CASE_ID
LEFT JOIN CUSTOMER_OPS_DB.RAW.SERVICE_EVENTS_RAW e ON i.CASE_ID = e.CASE_ID
GROUP BY i.AGENT_ID;
 
-- ============================================================================
-- SECTION 5: VERIFY VIEWS CREATION
-- ============================================================================
 
SHOW VIEWS IN SCHEMA CUSTOMER_OPS_DB.MART;
 
-- Test main view
SELECT COUNT(*) AS TOTAL_RECORDS FROM MART_CASE_SUMMARY;
SELECT TOP 5 * FROM MART_CUSTOMER_ANALYTICS;
SELECT * FROM MART_CHANNEL_PERFORMANCE;
SELECT TOP 5 * FROM MART_AGENT_PERFORMANCE;
 