-- ============================================================================
-- CUSTOMER OPS PLATFORM - SNOWFLAKE SETUP
-- File: 01_setup.sql
-- Purpose: Create warehouse, database, and schemas
-- ============================================================================

CREATE OR REPLACE WAREHOUSE CUSTOMER_OPS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE CUSTOMER_OPS_DB;

CREATE OR REPLACE SCHEMA CUSTOMER_OPS_DB.RAW;
CREATE OR REPLACE SCHEMA CUSTOMER_OPS_DB.TRANSFORM;
CREATE OR REPLACE SCHEMA CUSTOMER_OPS_DB.MART;

SHOW SCHEMAS IN DATABASE CUSTOMER_OPS_DB;

USE WAREHOUSE CUSTOMER_OPS_WH;
USE DATABASE CUSTOMER_OPS_DB;
USE SCHEMA CUSTOMER_OPS_DB.RAW;

CREATE OR REPLACE STAGE CUSTOMER_OPS_STAGE
  FILE_FORMAT = (
    TYPE = CSV 
    SKIP_HEADER = 1 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'nan')
  );

SELECT CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();